title: Xin (Jennifer) Chen
logo: /assets/img/profile.JPG
#description: text below image
#show_downloads: false
theme: jekyll-theme-minimal
# markdown: kramdown

# # Custom CSS
# sass:
#   style: compressed

# include:
#   - assets/style.css
