title: Xin (Jennifer) Chen
# logo: /assets/img/profile.JPG 
avatar: "/assets/img/profile.JPG"
# logo: <img src="/assets/img/profile.JPG" alt="profile picture" style="width:150px; border-radius:50%;">
description: jenxchen (at) stanford (dot) edu

#show_downloads: false
theme: jekyll-theme-minimal
markdown: kramdown

# # Custom CSS
sass:
  style: compressed

include:
- assets/style.css
