title: Xin (Jennifer) Chen
#logo: /assets/img/profile.JPG
logo:: <img src="/assets/img/profile.JPG" style="width:100px; height:auto;" />
#description: text below image
#show_downloads: false
theme: jekyll-theme-minimal
